### ISSUE TITLE
Parameter virtualhost should be virtual_host in documentation

### ISSUE THREAD

**Issue by horshack** [Humanstate/net-amqp-rabbitmq#15]
in https://metacpan.org/pod/Net::AMQP::RabbitMQ::PP#connect
you write

$mq->connect(
        host           => "localhost",
        port           => 5672,
        timeout        => undef,
        username       => 'guest',
        password       => 'guest',
        virtualhost    => '/',
        heartbeat      => undef,
        socket_timeout => 5,
        frame_max      => 131072,
);

but the Parameter "virtualhost" should be named "virtual_host" because

Net::AMQP::RabbitMQ::PP::connect(/usr/local/share/perl/5.24.1/Net/AMQP/RabbitMQ/PP.pm:87):
87:             my $virtualhost = $args{virtual_host} || '/';

**Comment by leejo** [comment]
Thanks @horshack - i'll fix this shortly.
